name: Build RustDesk with Stealth

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: rustdesk/rustdesk
        submodules: true
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Modify main.rs
      run: |
        # 直接修改main.rs文件
        cp src/main.rs src/main.rs.backup
        
        # 使用Python进行精确修改
        python3 -c "
import re

with open('src/main.rs', 'r') as f:
    content = f.read()

# 在main函数中添加stealth检查
new_content = re.sub(
    r'(fn main\s*\(\s*\)\s*\{)',
    r'\1\n    // Stealth mode check\n    let args = std::env::args().collect::<Vec<String>>();\n    if args.contains(&\"--stealth\".to_string()) {\n        println!(\"Stealth mode enabled\");\n    }',
    content
)

with open('src/main.rs', 'w') as f:
    f.write(new_content)

print('Main.rs modified successfully')
"
        
    - name: Build
      run: cargo build --release
      
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-stealth
        path: target/release/rustdesk
